# Generated by Django 4.0.3 on 2022-05-23 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_zone', to='orders.zone', verbose_name='зона в которой находится отель'),
        ),
        migrations.AddField(
            model_name='yurt',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yurt_zone', to='orders.zone', verbose_name='зона в которой находится'),
        ),
    ]
