# Generated by Django 4.0.3 on 2022-05-23 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_hotel_zone_yurt_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='orders.album'),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_room', to='orders.album'),
        ),
        migrations.AlterField(
            model_name='news',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='orders.album'),
        ),
        migrations.AlterField(
            model_name='yurt',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yurt', to='orders.album'),
        ),
    ]
